[privacy]
# enable folder listing, if true, will list all files in the wildcard folders at /wildcards
# if false, you need to know the path to the file to access it
enable_folder_listing = true
# if false, only files ending in .txt will be served. if true, any file will be served
arbitrary_files = false
# if true, allow path traversal attacks (e.g. /../foo.txt). this can and will expose files outside of the wildcard folder
# to a bad actor. only enable if you know what you're doing and/or don't mind getting pwned.
path_traversal = false

[server]
# default port is 8080, change if you want to
port = 8080
# change to 0.0.0.0 to allow external connections
bind = "127.0.0.1"

[files]
# list of allowed wildcard folders. paths are relative to server.py
wildcard_folders = ["./wildcards"]
